### PR TITLE
Update to Tiled 1.2.0

### PR DESCRIPTION
**Pull request by umago**

### CODE REVIEW

**Comment by TingPing** [comment]
Bot, build

**Comment by umago** [comment]
Is the bot working ? Not sure whether it would leave a comment here or if I should check the results somewhere else (@TingPing if that's the case, do you have a link handy ?)

**Comment by TingPing** [comment]
Builds get logged here: https://flathub.org/builds/#/?numbuilds=300

I can't see the result on there so the bot may not have picked it up, will try again.

**Comment by TingPing** [comment]
bot, build

**Pull request merged**
