### PR TITLE
Update runtime

### PR DESCRIPTION
**Pull request by ghost**
Update out-of-date runtime

### CODE REVIEW

**Comment by bjorn** [comment]
https://github.com/mapeditor/tiled/pull/3937 adds the now required developer name. We can either wait with this until the Tiled 1.11 release or [the patch](https://patch-diff.githubusercontent.com/raw/mapeditor/tiled/pull/3937.patch) will need to be added to this repository for now.

**Comment by bjorn** [comment]
Unfortunately it appears Qt 6.6.3 also contains the change that broke the rendering of group boxes:

image

I fixed this in https://github.com/mapeditor/tiled/commit/93f6fef14052e6797440e3f4c4a093f7507b2249 (and tweaked it in https://github.com/mapeditor/tiled/commit/cf21779e55f2ed25f1c36498d20646cbe412da17), but I thought this change was specific to Qt 6.7, so the `QT_VERSION` checks in those patches will need to be adjusted (https://github.com/mapeditor/tiled/pull/3940).

**Comment by ghost** [comment]
You can use 6.7 version of KDE Platform. I used 6.6 due to it was the most used one

resim

https://flathub.org/statistics

**Comment by bjorn** [comment]
Let's wait with the runtime update until Tiled 1.11 is ready then.

**Pull request merged**
