### PR TITLE
Update Runtime to 6.5

### PR DESCRIPTION
**Pull request by JakobDev**

### CODE REVIEW

**Comment by bjorn** [comment]
Alright, it's failing to build Qbs due to the following error:
```
Can't open perl script "/usr/./libexec/syncqt.pl": No such file or directory
make[2]: *** [src/lib/scriptengine/CMakeFiles/qbsscriptengine_autogen.dir/build.make:95: src/lib/scriptengine/include/QtScript/qscriptengine.h] Error 2
make[1]: *** [CMakeFiles/Makefile2:1136: src/lib/scriptengine/CMakeFiles/qbsscriptengine_autogen.dir/all] Error 2
```
Likely the best way to fix this is to also update the version of Qbs from the now pretty old `v1.21.0`. Could probably just try the current `v2.1.2` version.

**Comment by bjorn** [comment]
Arg, now we're running into the `math.h` include issue again:
```
ERROR: /usr/bin/g++ -O2 -Wall -Wextra -m64 -pipe -fexceptions -fvisibility=default -fPIC -DNDEBUG '-DQT_DISABLE_DEPRECATED_BEFORE=QT_VERSION_CHECK(5,15,0)' -DQT_NO_DEPRECATED_WARNINGS -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_FOREACH -DQT_NO_URL_CAST_FROM_STRING -DQT_QML_LIB -DQT_WIDGETS_LIB -DQT_QMLINTEGRATION_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NO_DEBUG -I/run/build/tiled/src/tiledapp -I/run/build/tiled/src/tiled -I/run/build/tiled/src/qtsingleapplication/src -I/run/build/tiled/src/libtiled -I/run/build/tiled/release/tiled.1920fdf8/qt.headers -isystem/usr/include -isystem/usr/include/QtQml -isystem/usr/include/QtWidgets -isystem/usr/include/QtQmlIntegration -isystem/usr/include/QtNetwork -isystem/usr/include/QtGui -isystem/usr/include/QtCore -isystem/usr/mkspecs/linux-g++ -std=c++17 -o /run/build/tiled/release/tiled.1920fdf8/3a52ce780950d4d9/main.cpp.o -c /run/build/tiled/src/tiledapp/main.cpp
ERROR: In file included from /usr/include/QtCore/qnumeric.h:13,
                 from /usr/include/QtCore/qglobal.h:61,
                 from /usr/include/QtCore/qcoreapplication.h:7,
                 from /usr/include/QtCore/QCoreApplication:1,
                 from /run/build/tiled/src/tiledapp/commandlineparser.h:24,
                 from /run/build/tiled/src/tiledapp/main.cpp:23:
/usr/include/c++/12.2.0/cmath:45:15: fatal error: math.h: No such file or directory
   45 | #include_next <math.h>
      |               ^~~~~~~~
compilation terminated.
```
I've [run into this before](https://github.com/flathub/org.mapeditor.Tiled/pull/21) and back then solved by [reverting back to Qbs 1.21](https://github.com/flathub/org.mapeditor.Tiled/pull/21#issuecomment-1469550674).

**Comment by bjorn** [comment]
@JakobDev Now the build is successful. I wonder, is there a reason to update immediately, or would it make sense to wait with this until the next Tiled release?

**Comment by JakobDev** [comment]
6.4 is EOL

**Pull request merged**
