### PR TITLE
Update org.mapeditor.Tiled.json

### PR DESCRIPTION
**Pull request by bjorn**
* Updated to Tiled 0.10.0
* Updated to Qt 6.4
* Updated to Qbs 1.24.1

### CODE REVIEW

**Comment by TingPing** [comment]
qbs fails to build trying to link to `-lstdc++fs`

**Comment by bjorn** [comment]
> qbs fails to build trying to link to `-lstdc++fs`

This must be using a GCC older than 9? Do you know if it's possible to make it use a more recent GCC?

**Comment by TingPing** [comment]
`org.kde.Sdk//6.4` has GCC 12.1.0.

**Comment by bjorn** [comment]
> `org.kde.Sdk//6.4` has GCC 12.1.0.

Yeah, I noticed that in the header paths too, but then I can't explain that failure when building Qbs with qmake.

Anyway, I switched the Qbs build to cmake and then it compiled Qbs 1.24.1 fine. However, I ran into another weird issue in #21.

**Pull request merged**
